language: python
matrix:
  include:
  - env: BUILD_NAME=vhdl
    python: '3.6'
    os: linux
    sudo: required
    dist: trusty
    before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y gnat-4.8 zlib1g-dev
    - sudo apt-get install -y llvm-3.5-dev llvm-3.5-tools libedit-dev
    before_script:
    - git clone --depth 1 https://github.com/tgingold/ghdl.git ghdl
    - cd ghdl
    - mkdir build-llvm
    - cd build-llvm
    - ../configure --prefix=../../install-ghdl-llvm/ --with-llvm-config=llvm-config-3.5
    - make
    - make install
    - cd ../../
    - export PATH=$PATH:install-ghdl-llvm/bin/
    - git clone --recursive https://github.com/VUnit/vunit.git
    - cd vunit
    - python setup.py install
    - cd ..

  - env: BUILD_NAME=jack
    python: '3.6'
    os: linux
    sudo: required
    dist: trusty
    before_install:
    - sudo apt-get install -y caca-utils
    install:
    - pip install -r requirements.txt

  - env: BUILD_NAME=assembly
    python: '3.6'
    os: linux
    sudo: required
    dist: trusty
    before_install:
    - sudo apt-get install -y caca-utils
    install:
    - pip install -r requirements.txt

  - env: BUILD_NAME=assembler
    python: '3.6'
    os: linux
    sudo: required
    dist: trusty
    
  - env: BUILD_NAME=vmtranslator
    python: '3.6'
    os: linux
    sudo: required
    dist: trusty
    

addons:
  apt:
    packages:
      - oracle-java8-installer

script:
- bash tests.sh $BUILD_NAME

notifications:
  email: false
  slack: elementosdesistemas:ofJV6uLFlgvMBAR0YDOgeGwl#github_privado
